---
## General pipeline parameters:

# Name of the pipeline:
#pipeline: "Amplicon Sequencing Pipeline"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "/home/epicwl/c010-datasets/Internal/amplicon_seq_pipeline/test_run/"
# Repository URL:
#repo: ""

## Pipeline-specific parameters:

threads: 4

#Adapter sequence for trimming:
adapters: "/home/epicwl/c010-datasets/Internal/amplicon_seq_pipeline/Pipeline/adapters.fasta"

#Reference genome for alignment with bismark
Bismark_reference: "/home/epicwl/ngs_share/bcbio/genomes/Hsapiens/hg19/bismark/"


#Options for QC report
bed: "/C010-datasets/Internal/amplicon_seq_pipeline/test_maxi/sites_analysis.bed"
meta: "/C010-datasets/Internal/amplicon_seq_pipeline/test_maxi/meta.txt"
