## General pipeline parameters:
# Name of the pipeline:
pipeline: "Amplicon Sequencing Pipeline"
# ABSOLUTE path to directory holding the working directory:
workdir_top: "/home/epicwl/c010-datasets/Internal/amplicon_seq_pipeline/test_run/"
# Repository URL:
repo: "https://github.com/HeyLifeHD/amplicon_bisulfite_seq_pipeline/"
## Pipeline-specific parameters:
threads: 4
#Reference genome for alignment with bismark
Bismark_reference: "/home/epicwl/ngs_share/bcbio/genomes/Hsapiens/hg19/bismark/"
#Options for QC report: specify sites to be analyzed in a bed file and meta file containing sample names and file names
bed: "/home/epicwl/c010-datasets/Internal/amplicon_seq_pipeline/test_maxi/sites_analysis.bed"
meta: "/home/epicwl/c010-datasets/Internal/amplicon_seq_pipeline/test_maxi/meta.txt"
