---
title: "Introduction - AMP"
author: "Maximilian Schönung"
date: "12/18/2018"
output: html_document
---


<style>
body {
text-align: justify}
</style>

<br>

### Browser Compatibility 

AmpliconDesign is compatible with the following browsers:

| &emsp;   OS   	|   Version    	|    Chrome    	|    Safari  	|     Firefox   | &emsp;&emsp; Microsoft Edge  	|
|:-------:	|--------------	|:------------:	|:---------: 	| :-----------:	|:----------------:	|
|  Linux &emsp;&emsp; 	| Ubuntu 18.04 &emsp;&emsp;	| 71.0.3578.80 &emsp;&emsp;	|   N/A     &emsp;&emsp;&emsp;&emsp; 	|   Quantum    	|   &emsp;&emsp;     N/A       	|
|  MacOS &emsp;&emsp; 	| Mojave      &emsp;&emsp; 	|  Not tested  &emsp;&emsp;	| 12.0.2   &emsp;&emsp; &emsp;&emsp; 	|   Quantum   	|    &emsp;&emsp;    N/A       	|
| Win  &emsp;&emsp;    	| 10          &emsp;&emsp; 	|  Not tested  &emsp;&emsp;	|   N/A    &emsp;&emsp;&emsp;&emsp; 	|   Quantum   	| &emsp;&emsp; 11.0.10240.18036 	|


<br>

### Impressum 

AmpliconDesign in hosted by the [Section of Translational Cancer Epigenomics at the German Cancer Research Center (DKFZ) & National Center for Tumor Diseases (NCT) Heidelberg](http://www.translational-cancer-epigenomics.de). <br>
<br>
 **Section of Translational Cancer Epigenomics** <br>
Im Neuenheimer Feld 280 <br>
69120 Heidelberg <br>
Germany 


<br>

### Contributing Authors

Maximilian Schönung <br>
Pascal Bawidamann <br>
Jana Hess <br>
Sina Stäble <br>
Joschka Hey <br>
Jens Langstein <br>
Yassen Assenov <br>
Dieter Weichenhan <br>
Pavlo Lutsik <br>
Daniel Lipka <br>
<br>


### Third Party Software

AmpliconDesign uses primer3 (v1.1.4) with bisulfite adjusted parameters. <br>
Primer3 is a free and open-source tool which protected by the GNU General Public License. <br>
<br>
primer3 release 1.1.3 ---------------------<br> Copyright (c) 1996,1997,1998,1999,2000,2001,2004,2006,2007,2008<br> Whitehead Institute for Biomedical Research, Steve Rozen (http://jura.wi.mit.edu/rozen), and Helen Skaletsky All rights reserved. Most of primer3 is released under the following _new_ BSD license: Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. * Neither the names of the copyright holders nor contributors may be used to endorse or promote products derived from this software without specific prior written permission. <br>THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNERS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. <br> The oligtm library and tests are released under the GPL.<br>See file src/gpl.txt or go to http://www.gnu.org/licenses/gpl-2.0.txt.

<br>

MassArray amplicon plots are generated by using the R Bioconductor MassArray package: <br>
Thompson RF, Suzuki M, Lau KW, Greally JM. A pipeline for the quantitative analysis of CG dinucleotide methylation using mass spectrometry. Bioinformatics. 2009;25(17):2164-70. 

