---
title: "Introduction - MA"
author: "Maximilian Schönung"
date: "12/18/2018"
output: html_document
---

<br>

The MassArray section of AmpliconDesign allows the design and selection of primer pairs for EpiTYPER MassArray. Users need to provide the web service with genome coordinates from common reference genomes. The web service extract DNA sequences from the respective regions, performs bisulfite conversion, genome annotation with common features and determines which CpGs in the respective amplicons can be assayed by MassArray. A graphical output and automated primer design allow a user friendly choice of suitable primers. 

<br>

The following input parameters can be specified:

<br>


#### **Select Genome**
Selection of the genome assembly. Users can choose between GRCh38/hg38, GRCh27/hg19 and GRCm38/mm10.

#### **Enter genomic coordinate**
Genomic Coordinates of the CpG site of interest can be inserted. *NOTE: No comma separation!* (Example: chr19:43203328-43203389) 

<br>
<br>
